# https://www.elastic.co/guide/en/beats/filebeat/7.8/running-on-docker.html#_custom_image_configuration
ARG version

FROM docker.elastic.co/beats/filebeat:$version
# overwrite their default config
COPY ./configs/filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
RUN chmod go-w /usr/share/filebeat/filebeat.yml
USER filebeat
